// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_ArcStep;
extern lv_obj_t * ui_ArcTemperature;
extern lv_obj_t * ui_ArcHumidity;
extern lv_obj_t * ui_LabelStepNum;
extern lv_obj_t * ui_LabelHumidityNum;
extern lv_obj_t * ui_LabelTemperatureNum;
extern lv_obj_t * ui_ImgStep;
extern lv_obj_t * ui_ImgTemperature;
extern lv_obj_t * ui_ImgHumidity;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_LabelWeek;
extern lv_obj_t * ui_ImgTired;
extern lv_obj_t * ui_ImgBlueTooth;
// SCREEN: ui_heartScreen
extern void ui_heartScreen_screen_init(void);
extern void ui_event_heartScreen(lv_event_t * e);\
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_heartScreen;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image_heart;
//extern lv_obj_t * ui_img_heart_png;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui____initial_actions0;
// SCREEN: ui_LightScreen
void ui_LightScreen_screen_init(void);
void ui_event_LightScreen(lv_event_t * e);
extern lv_obj_t * ui_LightScreen;
void ui_event_ImgLight(lv_event_t * e);
extern lv_obj_t * ui_ImgLight;
// SCREEN: ui_StepScreen
void ui_StepScreen_screen_init(void);
void ui_event_StepScreen(lv_event_t * e);
extern lv_obj_t * ui_StepScreen;
extern lv_obj_t * ui_imgtimer;
extern lv_obj_t * ui_Imgcalorle;
extern lv_obj_t * ui_Imgrunbx;
extern lv_obj_t * ui_LabtimeNum;
extern lv_obj_t * ui_LabStepNum;
extern lv_obj_t * ui_LabcalorleNum;
extern lv_obj_t * ui_Image_sleep;
// SCREEN: ui_SleepScreen
void ui_SleepScreen_screen_init(void);
void ui_event_SleepScreen(lv_event_t * e);
extern lv_obj_t * ui_SleepScreen;
extern lv_obj_t *chart;
extern lv_chart_series_t *ser1;
extern lv_timer_t *chart_timer;


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Calendar1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_step_png);    // assets/Step.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets/Temperature.png
LV_IMG_DECLARE(ui_img_drop_png);    // assets/Drop.png
LV_IMG_DECLARE(ui_img_tired_png);    // assets/tired.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/Bluetooth.png
LV_IMG_DECLARE(ui_img_heart_png);    // assets/heart.png
LV_IMG_DECLARE(ui_img_oxysatura_png);    // assets/Oxysatura.png
LV_IMG_DECLARE(ui_img_shoudian_png);    // assets/shoudian.png
LV_IMG_DECLARE(ui_img_timer_png);    // assets/timer.png
LV_IMG_DECLARE(ui_img_calorie_png);    // assets/calorie.png
LV_IMG_DECLARE(ui_img_1576808831);    // assets/bx-run.png
LV_IMG_DECLARE(ui_img_wave1_png);    // assets/calorie.png
LV_IMG_DECLARE(ui_img_wave2_png);    // assets/bx-run.png
LV_IMG_DECLARE(ui_img_heart);    // assets/bx-run.png
LV_IMG_DECLARE(ui_img_sleep_png);    // assets/bx-run.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
