// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void flashlight_switch(lv_event_t * e);
void mode_run_start(lv_event_t * e);
void mode_run_stop(lv_event_t * e);
void set_today_date(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
