// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "stdio.h"
#include "tft.h"
#include "freertos.h"
#include "event_groups.h"
#include "runmode.h"
#include "stm32f4xx_rtc.h"

extern bool is_screen_off;

void flashlight_switch(lv_event_t *e)
{
	// 获取当前屏幕的背景颜色
	lv_color_t color = lv_obj_get_style_bg_color(ui_LightScreen, LV_PART_MAIN | LV_STATE_DEFAULT);

	// 比较当前颜色是否为白色
	if (lv_color_hex(0xFFFFFF).full == color.full)
	{
		// 如果是白色，则设置为黑色
		lv_obj_set_style_bg_color(ui_LightScreen, lv_color_hex(0x000000), LV_PART_MAIN);
	}
	else
	{
		// 如果不是白色，则设置为白色
		lv_obj_set_style_bg_color(ui_LightScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
	}
}

void offScreen_switch(lv_event_t *e)
{
	lcd_display_on(false);
	is_screen_off = true;
}


void set_today_date(lv_event_t *e)
{
	// 获取rtc时钟
	RTC_DateTypeDef RTC_DateStruct;
	RTC_GetDate(RTC_Format_BIN, &RTC_DateStruct);

	uint32_t year = RTC_DateStruct.RTC_Year;
	uint32_t month = RTC_DateStruct.RTC_Month;
	uint32_t day = RTC_DateStruct.RTC_Date;

	year += 2000;

	lv_calendar_set_today_date(ui_Calendar1, year, month, day);
	lv_calendar_set_showed_date(ui_Calendar1, year, month);
}
