// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_LightScreen_screen_init(void)
{
    ui_LightScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LightScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LightScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgLight = lv_img_create(ui_LightScreen);
    lv_img_set_src(ui_ImgLight, &ui_img_shoudian_png);
    lv_obj_set_width(ui_ImgLight, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_ImgLight, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_ImgLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgLight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ImgLight, ui_event_ImgLight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LightScreen, ui_event_LightScreen, LV_EVENT_ALL, NULL);

}
