// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x032320), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, 38);
    lv_obj_set_y(ui_LabelTime, -2);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "11:40:33");
    lv_obj_set_style_text_color(ui_LabelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcStep = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcStep, 240);
    lv_obj_set_height(ui_ArcStep, 240);
    lv_obj_set_align(ui_ArcStep, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcStep, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_ArcStep, 0, 5000);
    lv_arc_set_value(ui_ArcStep, 0);
    lv_arc_set_bg_angles(ui_ArcStep, 90, 270);
    lv_obj_set_style_arc_color(ui_ArcStep, lv_color_hex(0xFF6666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcStep, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcStep, 17, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcStep, lv_color_hex(0xFF6666), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcStep, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcStep, 17, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcStep, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcStep, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcTemperature = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcTemperature, 190);
    lv_obj_set_height(ui_ArcTemperature, 190);
    lv_obj_set_align(ui_ArcTemperature, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcTemperature, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_ArcTemperature, 0, 60);
    lv_arc_set_value(ui_ArcTemperature, 0);
    lv_arc_set_bg_angles(ui_ArcTemperature, 90, 270);
    lv_obj_set_style_arc_color(ui_ArcTemperature, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemperature, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemperature, 17, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcTemperature, lv_color_hex(0xFFFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemperature, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemperature, 17, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcTemperature, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemperature, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcHumidity = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcHumidity, 140);
    lv_obj_set_height(ui_ArcHumidity, 140);
    lv_obj_set_align(ui_ArcHumidity, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcHumidity, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_ArcHumidity, 2);
    lv_arc_set_bg_angles(ui_ArcHumidity, 90, 270);
    lv_obj_set_style_arc_color(ui_ArcHumidity, lv_color_hex(0x00AAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHumidity, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcHumidity, 17, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcHumidity, lv_color_hex(0x00AAFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHumidity, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcHumidity, 17, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcHumidity, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcHumidity, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelStepNum = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelStepNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStepNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStepNum, 32);
    lv_obj_set_y(ui_LabelStepNum, -115);
    lv_obj_set_align(ui_LabelStepNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStepNum, "0");
    lv_obj_set_style_text_color(ui_LabelStepNum, lv_color_hex(0xFF6666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStepNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumidityNum = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelHumidityNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumidityNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumidityNum, 32);
    lv_obj_set_y(ui_LabelHumidityNum, -62);
    lv_obj_set_align(ui_LabelHumidityNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumidityNum, "0%");
    lv_obj_set_style_text_color(ui_LabelHumidityNum, lv_color_hex(0x00AAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHumidityNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemperatureNum = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelTemperatureNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemperatureNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemperatureNum, 32);
    lv_obj_set_y(ui_LabelTemperatureNum, -90);
    lv_obj_set_align(ui_LabelTemperatureNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemperatureNum, "0°C");
    lv_obj_set_style_text_color(ui_LabelTemperatureNum, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemperatureNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgStep = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ImgStep, &ui_img_step_png);
    lv_obj_set_width(ui_ImgStep, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImgStep, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImgStep, 32);
    lv_obj_set_y(ui_ImgStep, 120);
    lv_obj_set_align(ui_ImgStep, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgStep, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgStep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgStep, lv_color_hex(0xFF6562), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImgStep, 225, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgTemperature = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ImgTemperature, &ui_img_temperature_png);
    lv_obj_set_width(ui_ImgTemperature, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImgTemperature, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImgTemperature, 32);
    lv_obj_set_y(ui_ImgTemperature, 90);
    lv_obj_set_align(ui_ImgTemperature, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgTemperature, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgTemperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgTemperature, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImgTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgHumidity = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ImgHumidity, &ui_img_drop_png);
    lv_obj_set_width(ui_ImgHumidity, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImgHumidity, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImgHumidity, 32);
    lv_obj_set_y(ui_ImgHumidity, 55);
    lv_obj_set_align(ui_ImgHumidity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgHumidity, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgHumidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgHumidity, lv_color_hex(0x00AAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImgHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDate = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate, 69);
    lv_obj_set_y(ui_LabelDate, -32);
    lv_obj_set_align(ui_LabelDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDate, "2024-03-07");
    lv_obj_set_style_text_color(ui_LabelDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeek = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelWeek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeek, -5);
    lv_obj_set_y(ui_LabelWeek, -32);
    lv_obj_set_align(ui_LabelWeek, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeek, "week");
    lv_obj_set_style_text_color(ui_LabelWeek, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeek, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgTired = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ImgTired, &ui_img_tired_png);
    lv_obj_set_width(ui_ImgTired, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImgTired, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImgTired, 90);
    lv_obj_set_y(ui_ImgTired, -82);
    lv_obj_set_align(ui_ImgTired, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgTired, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgTired, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgBlueTooth = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ImgBlueTooth, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_ImgBlueTooth, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImgBlueTooth, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImgBlueTooth, 90);
    lv_obj_set_y(ui_ImgBlueTooth, -115);
    lv_obj_set_align(ui_ImgBlueTooth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBlueTooth, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBlueTooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgBlueTooth, lv_color_hex(0x013788), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImgBlueTooth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}
