// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "Max301.h"

void chart_update(lv_timer_t* timer) 
{
    lv_chart_set_next_value((lv_obj_t *)timer->user_data,ser1,n_sp02);
}

void ui_SleepScreen_screen_init(void)
{
//		static const lv_coord_t example_data[] = {
//    25, 26, 27, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
//		};
		
    ui_SleepScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SleepScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SleepScreen, lv_color_hex(0x032320), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SleepScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

	
    chart = lv_chart_create(ui_SleepScreen);  /* 创建图表部件 */
    lv_obj_set_size(chart, 180, 120);                 /* 设置图表大小 */
    lv_obj_align(chart, LV_ALIGN_CENTER, 20, 30);                             /* 中间对齐 */
    lv_chart_set_type(chart, LV_CHART_TYPE_LINE);     /* 设置折线图类型 */
		
	/* 添加数据序列 */
		ser1 = lv_chart_add_series(chart,lv_color_hex(0xff0000), LV_CHART_AXIS_PRIMARY_Y);
	
		lv_chart_set_point_count(chart, 10);  //设置数据点数量
		
		lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_Y, 0, 100);  //范围设置为 0~100
		
		lv_chart_set_div_line_count(chart, 10, 10);     //设置分隔线

		// 设置刻度线和刻度线标签
		lv_chart_set_axis_tick(chart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 6, 5, true, 40);
		lv_chart_set_axis_tick(chart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 10, 1, true, 30);
		
		
		lv_chart_cursor_t* cursor;
		cursor = lv_chart_add_cursor(chart, lv_palette_main(LV_PALETTE_GREEN), LV_DIR_BOTTOM);

		lv_point_t point = {20, 30};
		lv_chart_set_cursor_pos(chart, cursor, &point);

		
//		/* 将旧数据移到左边 */
//    lv_chart_set_update_mode(chart, LV_CHART_UPDATE_MODE_SHIFT);
    

    lv_timer_t *chart_timer = lv_timer_create(chart_update, 1000, chart);

    lv_timer_set_repeat_count(chart_timer, -1);
		
		ui_Image_sleep = lv_img_create(ui_SleepScreen);
    lv_img_set_src(ui_Image_sleep, &ui_img_sleep_png);
    lv_obj_set_width(ui_Image_sleep, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image_sleep, LV_SIZE_CONTENT);    /// 20
//    lv_obj_set_x(ui_Image_sleep, -65);
//    lv_obj_set_y(ui_Image_sleep, 0);
    //lv_obj_set_align(ui_Image_sleep, LV_ALIGN_CENTER);
		lv_obj_align_to(ui_Image_sleep, ui_SleepScreen, LV_ALIGN_TOP_MID, 0, 20);
    lv_obj_add_flag(ui_Image_sleep, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_sleep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//		chart = lv_chart_create(ui_SleepScreen);
//		lv_obj_set_size(chart, 180, 120);
//		lv_obj_align(chart, LV_ALIGN_CENTER, 20, 0);    
//		ser1 = lv_chart_add_series(chart,lv_color_hex(0xff0000), LV_CHART_AXIS_PRIMARY_Y);
//		lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_Y, 0, 100);
//		lv_chart_set_point_count(chart, 10);
//		lv_obj_set_style_bg_color(chart, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
//			//lv_obj_set_style_bg_opa(chart, 100, 0);
//		lv_chart_set_div_line_count(chart, 4, 10);
//		lv_obj_set_style_border_color(chart, lv_color_hex(0xFFFFFF), 0);
//		lv_chart_set_axis_tick(chart, LV_CHART_AXIS_PRIMARY_Y, 5, 3, 4, 2, true, 40);
//		chart_timer = lv_timer_create(chart_update, 600, chart);
//		lv_timer_set_repeat_count(chart_timer, -1);
		
    lv_obj_add_event_cb(ui_SleepScreen, ui_event_SleepScreen, LV_EVENT_ALL, NULL);

}
