// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

//void ui_StepScreen_screen_init(void)            //显示步数页面的
//{
//    ui_StepScreen = lv_obj_create(NULL);
//    lv_obj_clear_flag(ui_StepScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//    lv_obj_set_style_bg_color(ui_StepScreen, lv_color_hex(0x032320), LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_bg_opa(ui_StepScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//    ui_imgtimer = lv_img_create(ui_StepScreen);
//    lv_img_set_src(ui_imgtimer, &ui_img_timer_png);
//    lv_obj_set_width(ui_imgtimer, LV_SIZE_CONTENT);   /// 48
//    lv_obj_set_height(ui_imgtimer, LV_SIZE_CONTENT);    /// 48
//    lv_obj_set_x(ui_imgtimer, -80);
//    lv_obj_set_y(ui_imgtimer, -90);
//    lv_obj_set_align(ui_imgtimer, LV_ALIGN_CENTER);
//    lv_obj_add_flag(ui_imgtimer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//    lv_obj_clear_flag(ui_imgtimer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//    lv_obj_set_style_img_recolor(ui_imgtimer, lv_color_hex(0xFF9929), LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_img_recolor_opa(ui_imgtimer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//    ui_Imgcalorle = lv_img_create(ui_StepScreen);
//    lv_img_set_src(ui_Imgcalorle, &ui_img_calorie_png);
//    lv_obj_set_width(ui_Imgcalorle, LV_SIZE_CONTENT);   /// 48
//    lv_obj_set_height(ui_Imgcalorle, LV_SIZE_CONTENT);    /// 48
//    lv_obj_set_x(ui_Imgcalorle, -80);
//    lv_obj_set_y(ui_Imgcalorle, 90);
//    lv_obj_set_align(ui_Imgcalorle, LV_ALIGN_CENTER);
//    lv_obj_add_flag(ui_Imgcalorle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//    lv_obj_clear_flag(ui_Imgcalorle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//    lv_obj_set_style_img_recolor(ui_Imgcalorle, lv_color_hex(0xF6084A), LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_img_recolor_opa(ui_Imgcalorle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//    ui_Imgrunbx = lv_img_create(ui_StepScreen);
//    lv_img_set_src(ui_Imgrunbx, &ui_img_1576808831);
//    lv_obj_set_width(ui_Imgrunbx, LV_SIZE_CONTENT);   /// 48
//    lv_obj_set_height(ui_Imgrunbx, LV_SIZE_CONTENT);    /// 48
//    lv_obj_set_x(ui_Imgrunbx, -80);
//    lv_obj_set_y(ui_Imgrunbx, 0);
//    lv_obj_set_align(ui_Imgrunbx, LV_ALIGN_CENTER);
//    lv_obj_add_flag(ui_Imgrunbx, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//    lv_obj_clear_flag(ui_Imgrunbx, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//    lv_obj_set_style_img_recolor(ui_Imgrunbx, lv_color_hex(0x419DFF), LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_img_recolor_opa(ui_Imgrunbx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//    ui_LabtimeNum = lv_label_create(ui_StepScreen);
//    lv_obj_set_width(ui_LabtimeNum, LV_SIZE_CONTENT);   /// 1
//    lv_obj_set_height(ui_LabtimeNum, LV_SIZE_CONTENT);    /// 1
//    lv_obj_set_x(ui_LabtimeNum, 30);
//    lv_obj_set_y(ui_LabtimeNum, -90);
//    lv_obj_set_align(ui_LabtimeNum, LV_ALIGN_CENTER);
//    lv_label_set_text(ui_LabtimeNum, "00:00:00");
//    lv_obj_set_style_text_color(ui_LabtimeNum, lv_color_hex(0xFF9929), LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_text_opa(ui_LabtimeNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_text_font(ui_LabtimeNum, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

//    ui_LabStepNum = lv_label_create(ui_StepScreen);
//    lv_obj_set_width(ui_LabStepNum, LV_SIZE_CONTENT);   /// 1
//    lv_obj_set_height(ui_LabStepNum, LV_SIZE_CONTENT);    /// 1
//    lv_obj_set_align(ui_LabStepNum, LV_ALIGN_CENTER);
//    lv_label_set_text(ui_LabStepNum, "0");
//    lv_obj_set_style_text_color(ui_LabStepNum, lv_color_hex(0x419DFF), LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_text_opa(ui_LabStepNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_text_font(ui_LabStepNum, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

//    ui_LabcalorleNum = lv_label_create(ui_StepScreen);
//    lv_obj_set_width(ui_LabcalorleNum, LV_SIZE_CONTENT);   	/// 1
//    lv_obj_set_height(ui_LabcalorleNum, LV_SIZE_CONTENT);    /// 1
//    lv_obj_set_x(ui_LabcalorleNum, 0);
//    lv_obj_set_y(ui_LabcalorleNum, 90);
//    lv_obj_set_align(ui_LabcalorleNum, LV_ALIGN_CENTER);
//    lv_label_set_text(ui_LabcalorleNum, "0");
//    lv_obj_set_style_text_color(ui_LabcalorleNum, lv_color_hex(0xF6084A), LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_text_opa(ui_LabcalorleNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_text_font(ui_LabcalorleNum, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

//    //lv_obj_add_event_cb(ui_StepScreen, ui_event_StepScreen, LV_EVENT_ALL, NULL);

//}
